#!/bin/bash
# backup_to_tarball - Make a tarball of the filesystem hierarchy.
#
# Written by Aaron Bugher for the FSU Biology Department.
#
# LICENSE:
#
# Copyright (c) 2012, Florida State University
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are
# those of the authors and should not be interpreted as representing official
# policies, either expressed or implied, of the FreeBSD Project.
#
# END LICENSE

SYSNAME="example"
BACKUP_DIR="/home/username/backups"
OWNER="root:username"
TARFLAGS="cJ"

cd "${BACKUP_DIR}"
TARBALL="${SYSNAME}.$(date "+%Y-%m-%d").tar.xz"
touch "${TARBALL}"
chown "${OWNER}" "${TARBALL}"
chmod 0600 "${TARBALL}"

if
  tar \
    ${TARFLAGS} \
    --exclude='/lib/init/rw' \
    --exclude='/proc' \
    --exclude='/sys' \
    --exclude='/dev' \
    --exclude='/var/run/acpid.socket' \
    --exclude="${BACKUP_DIR}" \
    / \
    > "${TARBALL}"
then
  RET=0
  echo -e "\nOK, it's ready.  Don't leave that thing just lying around." >&2
else
  RET="${?}"
  echo -e "\nUh oh.  tar failed.  (${RET}):(" >&2
fi

exit "${RET}"
