#!/bin/bash
# capture 
#
# Capture audio and video as they are presented on screen and speakers.  (Any
# cameras or microphones are not involved.)  Record with codec FFV1.3 in
# Matroska (mkv) container format.


# hh:mm:ss
maximum_time='03:00:00'
start_time="$(date --iso-8601=s)"
file_extension='mkv'
video_codec='ffv1'
audio_codec='flac'
framerate='30'
output_dir=~/media/videos/screen_and_speakers_capture
output_file="${output_dir}/${start_time}.${file_extension}"
video_input="${DISPLAY}"
audio_input="$(pactl list short sources | awk '/monitor/ {print $1}')"

ffmpeg \
  -f x11grab -r "${framerate}" -i "${video_input}" \
  -f pulse -i "${audio_input}" \
  -t "${maximum_time}" -vcodec "${video_codec}" -level 3 -acodec "${audio_codec}" "${output_file}"
