#!/bin/bash
# capture 
#
# Capture audio and video as they are presented on screen and speakers.  (Any
# cameras or microphones are not involved.)  Record with codec FFV1.3 in
# Matroska (mkv) container format.

speaker_identifier='analog-stereo'

start_time="$(date --iso-8601=s)"
# hh:mm:ss
maximum_time='03:00:00'
framerate='30'

video_input="${DISPLAY}"
audio_input="$(pactl list short sources | awk "/${speaker_identifier}.*\.monitor/ {print \$1}")"

video_codec='ffv1'
video_codec_args=( -level 3 )
audio_codec='flac'

file_extension='mkv'
output_dir=~/media/videos/screen_and_speakers_capture
output_file="${output_dir}/${start_time}.${file_extension}"

ffmpeg \
  -f x11grab -r "${framerate}" -i "${video_input}" \
  -f pulse -i "${audio_input}" \
  -t "${maximum_time}" -vcodec "${video_codec}" "${video_codec_args[@]}" -acodec "${audio_codec}" "${output_file}"
