#!/bin/bash


# Source configuration as script.
# Lazy and potentially dangerous.
source ~/.config/monitors/config


unset external_attached
if xrandr | grep -v disconnected | grep -q ^"${external}"; then
  external_attached=yes
fi

if test set = "${external_attached:+set}"; then
  xrandr --output "${internal}" --off
  if test 'set' = "${external_resolution:+set}"; then
    xrandr --output "${external}" --mode "${external_resolution}"
  else
    xrandr --output "${external}" --auto
  fi
else
  xrandr --output "${external}" --off
  if test 'set' = "${internal_resolution:+set}"; then
    xrandr --output "${internal}" --mode "${internal_resolution}"
  else
    xrandr --output "${internal}" --auto
  fi
fi
