#!/bin/bash


function main() {
  # Strings:
  unset internal_output
  unset internal_resolution
  unset internal_rate
  # Booleans (set or not):
  unset internal_primary
  unset internal_with_external

  # Ordinal array of strings:
  #     External outputs will be configured in this order.  If all are
  #     specified as primary, the last successfully configured output will
  #     become primary.
  external_names=()

  # Hashes (associative arrays), indexed by name (as listed in
  # $external_names):
  #     $external_outputs[$name] must be set for each member of
  #     $external_outputs.  Other hashes are optional, but resolution must be
  #     set for rate to take effect.  (xrandr just works that way.  This script
  #     could potentially work around it by parsing $(xrandr) to find the
  #     default resolution for each output and passing that when one is not
  #     specified.  That is not presently implemented, though.)
  for var in \
    'external_outputs' \
    'external_resolutions' \
    'external_rates' \
    'external_primary' \
    ;
  do 
    unset "${var}"
    declare -A "${var}"
  done

  # Read configuration file.
  conf_file_path=~/.config/monitors/config
  if test -e "${conf_file_path}"; then
    source "${conf_file_path}"
  else
    warn "No configuration file found."
  fi

  
  connected_outputs_list=( $(find_connected_outputs) )
  # Stupid bash-ism to avoid searching the list.
  declare -A connected_outputs_hash
  for connected_output in "${connected_outputs_list[@]}"; do
    connected_outputs_hash["${connected_output}"]='connected'
  done

  unset output_configured
  if test 0 -ne "${#external_names[@]}"; then
    for name in "${external_names[@]}"; do
      if configure \
        "${external_outputs[${name}]}" \
        "${external_resolutions[${name}]}" \
        "${external_rates[${name}]}" \
        "${external_primary[${name}]}" \
        ;
      then
        output_configured='yes'
        output "Configured output requested by name:  '${name}'"
      else
        warn "Did not configure external output requested by name:  '${name}'"
      fi
    done
  fi

  if test '' != "${internal_name}"; then
    if test '' == "${output_configured}" -o '' != "${internal_with_external}"; then
      if configure \
        "${internal_output}" \
        "${internal_resolution}" \
        "${internal_rate}" \
        "${internal_primary}" \
        ;
      then
        output_configured='yes'
        output "Configured requested internal output."
      else
        warn "Did not configure requested internal output."
      fi
    fi
  fi

  if test '' == "${output_configured}"; then
    warn "No outputs configured as requested; trying defaults for any connected outputs."
    for connected_output in "${connected_outputs_list[@]}"; do
      if configure "${connected_output}"; then
        output_configured='yes'
      fi
    done
  fi

  if test '' == "${output_configured}"; then
    fail "Failed to configure any output."
  fi
}


function configure() {
  output="${1}"
  resolution="${2}"
  rate="${3}"
  primary="${4}"

  if test '' == "${output}"; then
    warn "Skipping unspecified output."
    return 1
  fi

  if test '' == "${connected_outputs_hash[${output}]}"; then
    warn "Skipping missing or disconnected output:  '${output}'"
    return 2
  fi

  args=( '--output' "${output}" )

  if test '' != "${resolution}"; then
    args+=( '--mode' "${resolution}" )
  else
    args+=( '--auto' )
  fi

  if test '' != "${rate}"; then
    args+=( '--rate' "${rate}" )
  fi

  if test '' != "${primary}"; then
    args+=( '--primary' )
  fi

  xrandr "${args[@]}"; ret="${?}"

  if test 0 -eq "${ret}"; then
    output "Configured output:  '${output}'"
  else
    warn "Failed to configure output:  '${output}'"
  fi

  return "${ret}"
}


function find_connected_outputs() {
  xrandr | awk '/[^ ]+ connected/ {print $1}'
}



function output() {
  printf '%s\n' "${1}"
}


function warn() {
  output "Warning:  ${1}" >&2
}


function error() {
  output "Error:  ${1}" >&2
}


function debug() {
  output "Debug:  ${1}" >&2
}


function fail() {
  error "${1}"
  exit "${2:-1}"
}


main "${@}"
