#!/bin/bash
# notehack
# notehack -n

notedir=~/notes/nethack

mkdir -p $notedir || {
  echo -e "Error:  Failed to mkdir ${notedir} ." >&2
  cd -
  exit 1
}

cd $notedir || {
  echo -e "Error:  Failed to cd ${notedir} ." >&2
  cd -
  exit 1
}

f=$(ls -tr | tail -n 1)

# -n for "new"
if test "${1}" = "-n"; then
  f=$(stamp).txt || {
    echo -e "Error:  Failed to stamp." >&2
    cd -
    exit 1
  }
  cp template.txt ${f} || {
    echo -e "Error:  Failed to copy template." >&2
    cd -
    exit 1
  }
fi 
  
vim ${f} || {
  echo -e "Error:  Failed to vim." >&2
  cd -
  exit 1
}

cd -
