#!/bin/bash
# notehack [-n]
#
# This program is free software. It comes without any warranty, to the extent
# permitted by applicable law. You can redistribute it and/or modify it under
# the terms of the Do What The Fuck You Want To Public License, Version 2, as
# published by Sam Hocevar. See WTFPL.txt or http://www.wtfpl.net/ for more
# details.

notedir=~/notes/nethack

mkdir -p $notedir || {
  echo -e "Error:  Failed to mkdir ${notedir} ." >&2
  cd -
  exit 1
}

cd $notedir || {
  echo -e "Error:  Failed to cd ${notedir} ." >&2
  cd -
  exit 1
}

f=$(ls -tr | tail -n 1)

# -n for "new"
if test "${1}" = "-n"; then
  f=$(stamp).txt || {
    echo -e "Error:  Failed to stamp." >&2
    cd -
    exit 1
  }
  cp template.txt ${f} || {
    echo -e "Error:  Failed to copy template." >&2
    cd -
    exit 1
  }
fi 
  
vim ${f} || {
  echo -e "Error:  Failed to vim." >&2
  cd -
  exit 1
}

cd -
