#!/bin/bash

clipboard_timeout="60s"


function main() {
  # It' mostly just xclip.
  output "Fetching password."
  xclip < <(pass show "${*}")
  output "Password retrieved.  Paste in the next:  ${clipboard_timeout}"

  # Wait ...
  sleep "${clipboard_timeout}"

  output "Time expired."
  # Now get that password off the clipboard.
  echo '' | xclip
  output "Clipboard cleared."
}


function output() {
  printf "%s:  %s\n" "${prefix}" "${*}"
}


function warn() {
  output "WARNING:  ${*}" 2>&1
}


function error() {
  output "ERROR:  ${*}" 2>&1
}


function fail() {
  error "${*}"
  exit 1
}


name="${0##*/}"
prefix="${name}"
main
