#!/bin/bash
#
# See:  ~/.gnupg/gpg-agent.conf


# SMALL SCREEN MODE:
# 
# Phones with little screens only have enough screen real estate for
# pinentry-curses when the keyboard is minimized.  Give the user a moment to do
# that before trying pinentry-curses.


# LIMITATIONS ON INTERACTIVITY:
# 
# When the script is run directly, it seems to work, but when it is called by
# gpg-agent for pinentry duty, problems start.
#
# echo or printf cause total failure:
#   gpg: public key decryption failed: No pinentry
#   gpg: decryption failed: No pinentry
# read fails to read.  Striking [Enter] does not terminate the timeout, and the
# keystroke is sent to pinentry-curses as the first character of the pass
# phrase.  Any prompt specified with -p is not displayed.
# 
# So this doesn't work:
#   read -p 'Strike [Enter] when ready for:  pinentry-curses' -t "${delay}" >&2
# ... and these don't work:
#   printf 'Strike [Enter] when ready for:  pinentry-curses\n'
#   echo 'Strike [Enter] when ready for:  pinentry-curses'
# The sleep statement seems to be OK.
#
# The real pinentry program seems to understand more than I do about how to
# handle input and output.


# ENVIRONMENT VARIABLES:
#
# This wrapper does not seem to have access to the same environment used by the
# program requiring pinentry.  (eg pass)  The pinentry program (this wrapper)
# is a child of gpg-agent.  gpg-agent is a child of init, eventually, but seems
# to inherit some of the environment (eg TERM, GPG_TTY) from the first program
# to attempt to interact with it.  (I guess it is launched on demand.)  The
# DISPLAY variable seems to be inherited from the program currently asking for
# pinentry to happen.
#
# PINENTRY_USER_DATA seems to be designed to be passed to the pinentry program
# from the program requring pinentry.  It also seems to be empty by default in
# my testing with pass.  I am adjusting my ~/.bashrc to (ab)use this variable
# to smuggle in the relevant TERM and DISPLAY variables for this wrapper to
# make decisions.  Watch for trouble, as I do not know what programs other than
# pass may do with PINENTRY_USER_DATA, and my use of eval may be unwise.


# REMAINING ISSUES:
#
# This causes an unnecessary pause when using a screen session locally.
#
# Some of the logic below may be redundant to the fallback functionality built
# in to pinentry-gtk-2.
#
# It would be good to provide a prompt explaining the delay.
#
# It would be good to allow skipping the delay.
#
# A longer delay would work well with a prompt and the ability to skip.
#
# A countdown might be nice.


delay=2         # seconds


eval "${PINENTRY_USER_DATA}"
if test '' = "${DISPLAY}" || grep -q '^screen' <<< "${TERM}"; then
  # Either X11 is not available, or this is a screen session.  X11 might not be
  # visible to the user, even if it is available to this program.  Avoid
  # relying on a graphical interface.
  sleep "${delay}"
  pinentry-curses
else
  # X11 is available, and this is not a screen session.  This could be a pure
  # graphical application.  This could also be a background process, such as a
  # file handler launched by the browser.  Avoid relying on a command line
  # interface.
  pinentry-gtk-2
fi
