#!/bin/bash
#
# Phones with little screens only have enough screen real estate for
# pinentry-curses when the keyboard is minimized.  Give the user a moment to do
# that before trying pinentry-curses.
#
# A countdown might be nice.


delay=5         # seconds

printf 'Strike [Enter] when ready for:  pinentry-curses\n'
read -t "${delay}"
pinentry-curses
