#!/bin/bash
#
# PS1="$(setPS1)"
#
#   Set PS1 to a fairly complex value.  Color will be used if available.
#
# setPS1 demo
#
#   Demonstrate every color and text decoration code by using the code while
#   printing the string representing the code.  For example, the code for
#   underlined cyan text on gray background should be displayed in underlined
#   cyan on a gray background.  This is intended to be used for developing this
#   script.


function main() {
  # Do some work to prepare for color output, even though colorless output
  # might be required.  This way, each part and its color can be set together,
  # reducing the chance of accidents while managing those arrays.
  #
  # See "colors by name" for the hashes of human readable color names to
  # machine readable color codes.
  #
  # A finer distinction might be appropriate between colors and other forms of
  # text decoration, but "color codes" control both.

  # This code marks the end of a string fragment affected by a prior color code.
  ps1_reset="$(ps1_color_code 0)"

  # This color will be used for informational text.
  if grep -q 'screen' <<< "${TERM}"; then
    ps1_default_color="$(ps1_color_code "${fg[gray]}" "${mod[underline]}")"
  else
    ps1_default_color="$(ps1_color_code "${fg[gray]}" "${mod[italics]}")"
  fi

  # This color will be used for punctuation separating elements.
  if test 0 = "${UID}"; then 
    ps1_splash_color="$(ps1_color_code "${fg[red]}" "${mod[invert]}")"
  else 
    ps1_splash_color="$(ps1_color_code "${fg[green]}" "${mod[none]}")"
  fi

  # ps_parts[0] gets ps1_colors[0], and so on.
  ps1_parts=()
  ps1_colors=()

  # return status of last command
  ps1_parts+=( '$(printf %3d "${?}")' )
  ps1_colors+=( "$(ps1_color_code "${bg[blue]}")" )

  # space
  ps1_parts+=( ' ' )
  ps1_colors+=( "${ps1_default_color}" )

  # user@host:pwd
  ps1_parts+=( '\u' )
  ps1_colors+=( "${ps1_default_color}" )

  ps1_parts+=( '@' )
  ps1_colors+=( "${ps1_splash_color}" )

  ps1_parts+=( '\h' )
  ps1_colors+=( "${ps1_default_color}" )

  ps1_parts+=( ':' )
  ps1_colors+=( "${ps1_splash_color}" )

  ps1_parts+=( '$(sed "s#^${HOME}#~#" <<< "${PWD}")' )
  ps1_colors+=( "${ps1_default_color}" )

  # privilege indicator (# or $)
  ps1_parts+=( "$(
    if test 0 = "${UID}"; then 
      printf '#'
    else 
      printf '$'
    fi
  )" )
  ps1_colors+=( "${ps1_splash_color}" )

  # space
  ps1_parts+=( ' ' )
  ps1_colors+=( "${ps1_default_color}" )

  # Report obvious misconfiguration.
  if ! test "${#ps1_colors[@]}" == "${#ps1_parts[@]}"; then
    printf 'ERROR:  %s\n' "setPS1 failed.  Number of colors does not match number of parts."
    exit 1
  fi

  # Handle colorless output.
  if ! terminal_has_color; then
    unset ps1_colors
    unset ps1_reset
  fi

  # Build the output string.
  ps1_value=''
  for i in "${!ps1_parts[@]}"; do
    ps1_value+="${ps1_colors[${i}]}${ps1_parts[${i}]}${ps1_reset}"
  done

  # Output the string.
  printf '%s' "${ps1_value}"
}


function terminal_has_color() {
  # Uncomment this temporarily to test colorless output:
  #
  # return 1

  if grep -qE 'color|xterm|screen' <<< "${TERM}"; then
    return 0
  else
    colors="$(tput colors 2>/dev/null)"
    if ! grep -q '[0-9]' <<< "${colors}"; then
      colors=0
    fi
    if test "${colors}" -ge 8; then
      return 0
    fi
  fi

  return 1
}


function ps1_color_code() {
  # Format a color code for use in PS1.
  color="${1}"
  modifier="${2:-0}"
  if test "${3:+set}" = 'set'; then
    background="${3}"
    printf '\\[\\033[%s;%s;%sm\\]' "${modifier}" "${color}" "${background}"
  else
    printf '\\[\\033[%s;%sm\\]' "${modifier}" "${color}"
  fi
}


function color_code() {
  # Format a color code for use by printf.
  color="${1}"
  modifier="${2:-0}"
  if test "${3:+set}" = 'set'; then
    background="${3}"
    printf '\\033[%s;%s;%sm' "${modifier}" "${color}" "${background}"
  else
    printf '\\033[%s;%sm' "${modifier}" "${color}"
  fi
}


function demo() {
  reset="$(color_code 0)"

  for b in $(sort <<< "${bg[@]}"); do
    for f in $(sort <<< "${fg[@]}"); do
      for m in $(sort <<< "${mod[@]}"); do
        printf "$(color_code "${f}" "${m}" "${b}") ${f};${m};${b} ${reset}"
      done
      printf '\n'
    done
  done
}


# colors by name

declare -A fg
fg[black]=30
fg[red]=31
fg[green]=32
fg[amber]=33
fg[blue]=34
fg[magenta]=35
fg[cyan]=36
fg[gray]=37

declare -A bg
bg[black]=40
bg[red]=41
bg[green]=42
bg[amber]=43
bg[blue]=44
bg[magenta]=45
bg[cyan]=46
bg[gray]=47

declare -A mod
mod[none]=0
mod[bright]=1
mod[dim]=2
mod[italics]=3
mod[underline]=4
mod[blink]=5
mod[blink]=6
mod[invert]=7
mod[invisible]=8
mod[strikethrough]=9


if test "${1}" = 'demo'; then
  demo
else
  main
fi
