#!/bin/bash

# This program is free software. It comes without any warranty, to the extent
# permitted by applicable law. You can redistribute it and/or modify it under
# the terms of the Do What The Fuck You Want To Public License, Version 2, as
# published by Sam Hocevar. See WTFPL.txt or http://www.wtfpl.net/ for more
# details.


# Very system-specific script to mount the large storage volume.  Supply the
# pass phrase to stdin - it's pipe-able.

/sbin/cryptsetup luksOpen /dev/sda storage
/bin/mount /storage
/usr/sbin/service transmission-daemon start
