#!/bin/bash

# Put one of these in sudoers:
# %sudo ALL= NOPASSWD: /usr/bin/tee /sys/power/state
# %sudo   ALL=(root:root) NOPASSWD: /usr/bin/tee /sys/power/state

function main() {
  state_specified="${1:-disk}"

  check-state

  pre-down
  down
  post-up
}


function check-state() {
  unset available
  states=( $(cat /sys/power/state) )

  for state_available in "${states[@]}"; do
    if test "${state_specified}" = "${state_available}"; then
      available=1
      break
    fi
  done

  if ! test 'set' = "${available:+set}"; then
    echo "State not available:  '${state_specified}'" >&2
    exit 1
  fi
}


function pre-down() {
  /usr/bin/xscreensaver-command --lock > /dev/null
  # Try to wait for lock.  Don't wait forever.
  for i in {1..10}; do
    if /usr/bin/xscreensaver-command --time | grep -q 'screen locked'; then
      break
    fi
  done
  # Wait for fade visual effect.
  sleep 5;
}


function down() {
  sudo /usr/bin/tee /sys/power/state > /dev/null <<< "${state_specified}"
}


function post-up() {
  ~/bin/monitors
}


main "${@}"
