#!/bin/bash
# testify - Create a testing copy of a file.
#
# Written by Aaron Bugher for the FSU Biology Department.
#
# LICENSE:
#
# Copyright (c) 2012, Florida State University
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are
# those of the authors and should not be interpreted as representing official
# policies, either expressed or implied, of the FreeBSD Project.
#
# END LICENSE

if [ "${#}" != "1" ]; then
	echo "Error: Specify exactly one (1) target to back up." >&2
	exit 1
fi

TESTFILE=$(echo "${1}" | sed 's/\(\..*\)$/.test.'"$(date "+%m-%d-%Y")"'\1/')
TESTLINK=$(echo "${1}" | sed 's/\(\..*\)$/.test\1/')

cp "${1}" "${TESTFILE}"
if [ -e "${TESTLINK}" ]
then
	if [ -h "${TESTLINK}" ]
	then rm "${TESTLINK}"
	else
		echo -e "Error: ${TESTLINK} exists and is not a symlink." >&2
		exit 1
	fi
fi

ln -s "${TESTFILE}" "${TESTLINK}"
echo -n "${TESTLINK}" | xclip -i
