#!/bin/bash
# torrent-cleanup

xmessageOptions="-center -buttons OK:0 -default OK"
ssh_target=ansible@files
credentials=transmission:$(pass show shared/transmission)
watch_dir=/storage/bittorrent/torrents
now="$(date +%s)"


function main {
  names=()
  files=()
  orphans=()

  while read name; do
    names+=( "${name}" )
  done < <(
    ssh "${ssh_target}" transmission-remote -n "${credentials}" -l \
      | sed -E 's/([^ ]* *){10}//' \
      | sort
  )

  while read file; do
    files+=( "${file}" )
  done < <(
    ssh "${ssh_target}" ls /storage/bittorrent/content/ \
      | sort
  )

  for file in "${files[@]}"; do
    orphan="yes"
    for name in "${names[@]}"; do
      if test "${file}" == "${name}"; then
        orphan="no"
        break
      fi
    done
    
    if test "yes" = "${orphan}"; then
      orphans+=( "${file}" )
    fi
  done

  for orphan in "${orphans[@]}"; do
    printf 'orphan:  %s\n' "${orphan}"
  done
}


function succeed {
  type="${1}"
  string="${2}"
  xmessage -timeout 2 ${xmessageOptions} "Successfully added ${type}:

  ${string}

"
}


function fail {
  type="${1}"
  string="${2}"
  ret="${3}"
  message="${4}"
  xmessage ${xmessageOptions} "Error:  Attempt to add ${type} returned status:  ${ret}

Target:

  ${string}

Message:

  ${message}
"

exit 1
}


main "${@}"
