#!/bin/bash
# untorrent { regex }
# torrent-first { regex }
# torrent-last { regex }

self_name="${0##*/}"


ssh_target=ansible@files
credentials=transmission:$(pass show shared/transmission)


function main {
  force='no'
  if 
    test '-f' = "${1}" \
    || test '--force' = "${1}"
  then
    shift 1
    force='yes'
  fi

  regex=
  for string in "${@}"; do
    if test '' = "${string}"; then
      echo "Empty argument matches everything.  Don't delete everything.  C'mon." >&2
      exit 1
    fi
    if grep -E '^.{0,4}$' <<< "${string}"; then
      if ! test 'yes' = "${force}"; then
        echo "Short strings can match a lot.  If you're sure , use '-f' ." >&2
        usage >&2
        exit 1
      fi
    fi
    if test '' = "${regex}"; then
      regex="${string}"
    else
      regex="${regex}|${string}"
    fi
  done

  echo "Getting torrent list."

  indices=( $(
    {
      ssh "${ssh_target}" transmission-remote -n "${credentials}" -l \
      || fail "Failed to get torrent list."
    } \
      | grep -iE "${regex}" \
      | awk '{print $1}' \
  ) )

  echo "Torrent list obtained.  Processing."

  for index in "${indices[@]}"; do
    index="$(sed 's/[^0-9]//g' <<< "${index}")"
    if test '' = "${index}"; then continue; fi
    echo "Matched torrent index:  '${index}'"
    case "${self_name}" in
      untorrent)
        if ssh "${ssh_target}" transmission-remote -n "${credentials}" -t "${index}" --remove-and-delete; then
          echo "... deleted."
        else
          warn "Failed to delete index:  '${index}'"
        fi
        ;;
      torrent-first)
        if ssh "${ssh_target}" transmission-remote -n "${credentials}" -t "${index}" -Bh; then
          echo "... prioritized."
        else
          warn "Failed to prioritize index:  '${index}'"
        fi
        ;;
      torrent-last)
        if ssh "${ssh_target}" transmission-remote -n "${credentials}" -t "${index}" -Bl; then
          echo "... deprioritized."
        else
          warn "Failed to deprioritize index:  '${index}'"
        fi
        ;;
      *)
        echo "I don't know what you want me to do or be." >&2
        exit 1
        ;;
    esac
  done;
}


function usage() {
  echo '  untorrent [-f|--force] <string> [string] ...'
  echo '  '
  echo '    Remove torrents and files where torrent name contains any specified'
  echo '    string in any capitalization pattern.'
  echo '  '
  echo '    Specify -f or --force as the first argument to proceed with unwisely'
  echo '    short strings.'
}


function warn() {
  echo "WARNING:  ${1}" >&2
}


function fail() {
  echo "ERROR:  ${1}" >&2
  exit "${2:-1}"
}


main "${@}"
