#!/bin/bash
# untorrent { regex }

ssh_target=ansible@files
credentials=transmission:$(pass show shared/transmission)


function main {
  string="${1}"

  if test '' = "${string}"; then
    echo "Empty argument matches everything.  Don't delete everything.  C'mon." >&2
    exit 1
  fi

  indices=( $(
    ssh "${ssh_target}" transmission-remote -n "${credentials}" -l \
      | grep -iE "${string}" \
      | awk '{print $1}'
  ) )

  for index in "${indices[@]}"; do
    if test '' = "${index}"; then continue; fi
    echo "Analyzing:  '${index}'"
    ssh "${ssh_target}" transmission-remote -n "${credentials}" -t "${index}" --remove-and-delete
  done;
}


main "${@}"
