#!/bin/bash


function unxz() {
  if type dd > /dev/null; then
    if type pv > /dev/null; then
      exec xz --decompress --stdout "${1}" | dd status=none bs=1M | pv -btra | dd status=none bs=1M of="${name}"
    else
      exec xz --decompress --stdout "${1}" | dd status=progress of="${name}"
    fi
  else
    exec xz --decompress --stdout "${1}" > "${name}"
  fi
}


function main() {
  echo "unxz:  Decompress the specified archive in the current directory." >&2
  echo "(Wrapper.  Original unxz writes to directory of specified archive.)" >&2

  if ! test 1 = "${#}"; then
    usage
    exit 1
  fi

  if ! grep -q '\.xz$' <<< "${1}"; then
    usage
    exit 2
  fi

  name_xz="${1##*/}"
  name="${name_xz%.xz}"

  unxz "${@}"
}


function usage() {
  echo -e "Usage:\n  unxz /path/to/file.xz" >&2
}


main "${@}"
